openapi: 3.0.3

info:
  title: user-api
  description: |-
    Сервис для работы с пользователем
  version: 1.0.0
externalDocs:
  description: GitHUb
  url: https://github.com/R3nnyWeb/Codest

servers:
  - url: /

tags:
  - name: users
    description: Пользователи
  - name: auth
    description: Аунтефикация

paths:

  /v1/users:
    post:
      tags:
        - users
      summary: Создание пользователя
      operationId: createUser
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateUserRequest'
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateUserResponse'
        400:
          $ref: '#/components/responses/Error'
        422:
          $ref: '#/components/responses/Error'
        500:
          $ref: '#/components/responses/Error'

  /v1/auth/login:
    post:
      tags:
        - auth
      summary: Аунтефикация
      operationId: login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoginResponse'
        401:
          $ref: '#/components/responses/Error'
        422:
          $ref: '#/components/responses/Error'
        500:
          $ref: '#/components/responses/Error'

components:
  responses:
    Error:
      description: Error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'

  schemas:
    CreateUserRequest:
      description: Создание пользователя
      type: object
      required:
        - username
        - password
      properties:
        username:
          type: string
          minLength: 1
          maxLength: 30
        password:
          minLength: 1
          maxLength: 30
          type: string

    CreateUserResponse:
      description: Пользователь
      type: object
      properties:
        userId:
          description: Идентификатор пользователя
          type: string
          format: uuid
          example: 803f29aa-cca4-4fe7-8254-e0005106cdc3

    LoginRequest:
      description: Аунтефикация
      type: object
      required:
        - username
        - password
      properties:
        username:
          type: string
        password:
          type: string

    LoginResponse:
      description: Аунтефикация
      type: object
      required:
        - token
      properties:
        token:
          description: JWT токен
          type: string
          example: 803f29aa-cca4-4fe7-8254-e0005106cdc3

    ErrorResponse:
      description: Данные об ошибке
      type: object
      required:
        - errorCode
        - errorMessage
      properties:
        errorMessage:
          description: Пользовательское сообщение об ошибке
          type: string
          minLength: 1
          example: Сервис временно недоступен
        errorCode:
          description: Код ошибки
          type: string
          minLength: 1
          maxLength: 8
          example: 01-Z99

  parameters:
    UserId:
      name: x-user-id
      in: header
      schema:
        type: string
        format: uuid
        example: 803f29aa-cca4-4fe7-8254-e0005106cdc3
      required: true


  headers:
    XTraceId:
      description: Идентификатор ответа
      schema:
        type: string
        minLength: 1
      required: true
