spring:
    application:
        name: codest-task
    data:
      mongodb:
        username: ${MONGO_USERNAME:codest}
        password: ${MONGO_PASSWORD:codest_db}
        database: ${MONGO_DATABASE:codest}
        port: ${MONGO_PORT:27017}
        host: ${MONGO_HOST:m.r3nny.ru}
        authentication-database: ${MONGO_AUTHENTICATION_DATABASE:admin}
server:
  port: ${PORT:8082}
