---
apiVersion: v1
kind: Service
metadata:
  name: svc-codest-frontend
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: codest-frontend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: codest-frontend
spec:
  replicas: 4
  selector:
    matchLabels:
      app: codest-frontend
  revisionHistoryLimit: 3
  progressDeadlineSeconds: 300
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      name: codest-frontend
      labels:
        app: codest-frontend
    spec:
      containers:
      - name: codest-frontend
        image: ghcr.io/r3nnyweb/codest-front:latest
        imagePullPolicy: "Always"
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            path: /
            port: 80
            scheme: HTTP
          initialDelaySeconds: 3
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /
            port: 80
            scheme: HTTP
          initialDelaySeconds: 3
          periodSeconds: 5
        resources:
          limits:
            memory: 128Mi
            cpu: 64m
