apiVersion: v1
kind: Service
metadata:
  name: svc-codest-api
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: codest-api
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: codest-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: codest-api
  revisionHistoryLimit: 2
  progressDeadlineSeconds: 300
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 2
  template:
    metadata:
      name: codest-api
      labels:
        app: codest-api
    spec:
      containers:
      - name: codest-api-ctr
        image: ghcr.io/r3nnyweb/codest-api:latest
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: 512Mi
            cpu: 0.5
        env:
          - name: JAVA_OPTS
            value: >-
              -Dconfig.file=/opt/app/config/application.conf
              -Xmx256m
              -XX: +AlwaysActAsServerClassMachine
              -XX: +UseG1GC