---
apiVersion: v1
kind: ConfigMap
metadata:
  name: codest-api-config
  labels:
    app: codest-api
data:
  application.conf: |
    openapi {
        management {
            file = "openapi/server/codest-api-openapi.yaml"
            enabled = true
            endpoint = "/openapi"
            swaggerui {
                enabled = true
                endpoint = "/swagger-ui"
            }
        }
    }

    kafka {
        cacheInvalidateConsumer {
            topics = "codest.cache.invalidate"
            pollTimeout = 250ms
            threads = 4
            driverProperties {
                bootstrap.servers: """
                          kafka-release.kafka.svc.cluster.local:9092
                      """
          security.protocol = "SASL_PLAINTEXT"
          sasl.mechanism = "SCRAM-SHA-256"
          sasl.jaas.config = "org.apache.kafka.common.security.scram.ScramLoginModule required username=\"user1\" password=\"${KAFKA_PASSWORD}\";"
                "group.id": "codest.api"${POD_NAME}
            }
        }
        runConsumer {
            topics = "codest.runner.response"
            pollTimeout = 250ms
            threads = 4
            driverProperties {
                bootstrap.servers: """
                          kafka-release.kafka.svc.cluster.local:9092
                      """
          security.protocol = "SASL_PLAINTEXT"
          sasl.mechanism = "SCRAM-SHA-256"
          sasl.jaas.config = "org.apache.kafka.common.security.scram.ScramLoginModule required username=\"user1\" password=\"${KAFKA_PASSWORD}\";"
                "group.id": "codest.api"
            }
        }
        producer {
             driverProperties {
                bootstrap.servers: """
                          kafka-release.kafka.svc.cluster.local:9092
                      """
          security.protocol = "SASL_PLAINTEXT"
          sasl.mechanism = "SCRAM-SHA-256"
          sasl.jaas.config = "org.apache.kafka.common.security.scram.ScramLoginModule required username=\"user1\" password=\"${KAFKA_PASSWORD}\";"
             }
             send-topic {
                  topic = "codest.runner.request"
             }
             cache-invalidate-topic {
                topic = "codest.cache.invalidate"
             }
        }
    }

    db {
        jdbcUrl = "jdbc:postgresql://dev-pg-postgresql:5432/codest"
        username = ${POSTGRES_USERNAME}
        password = ${POSTGRES_PASSWORD}
        schema = "public"
        poolName = "codest-task"
        maxPoolSize = 10
        minIdle = 2
    }

    security {
        key: ${JWT_SECRET}
    }

    cache {
        getTask {
             expireAfterWrite = "10000s"
             expireAfterAccess = "10000s"
             initialSize = 10
             maximusSize = 1000
        }
        testsByTaskId {
             expireAfterWrite = "10000s"
             expireAfterAccess = "10000s"
             initialSize = 10
             maximusSize = 1000
        }
        getAttempt {
             expireAfterWrite = "60s"
             expireAfterAccess = "60s"
             initialSize = 100
             maximusSize = 10000
        }
    }
---

apiVersion: v1
kind: Service
metadata:
  name: svc-codest-api
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: codest-api
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: codest-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: codest-api
  revisionHistoryLimit: 3
  progressDeadlineSeconds: 300
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      name: codest-api
      labels:
        app: codest-api
    spec:
      containers:
      - name: codest-api
        image: ghcr.io/r3nnyweb/codest-api:latest
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /system/liveness
            port: 8085
            scheme: HTTP
          initialDelaySeconds: 15
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /system/readiness
            port: 8085
            scheme: HTTP
          initialDelaySeconds: 15
          periodSeconds: 10
        resources:
          limits:
            memory: 512Mi
            cpu: 500m
        env:
          - name: JWT_SECRET
            valueFrom:
              secretKeyRef:
                name: jwt-secret
                key: secret
          - name: POSTGRES_USERNAME
            valueFrom:
              secretKeyRef:
                name: postgres
                key: user
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgres
                key: password
          - name: KAFKA_PASSWORD
            valueFrom:
              secretKeyRef:
                name: kafka
                key: password
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: JAVA_OPTS
            value: >-
              -Dconfig.file=/opt/app/config/application.conf
              -Xmx256m
              -XX:+AlwaysActAsServerClassMachine
              -XX:+UseG1GC
        volumeMounts:
          - name: config
            mountPath: "/opt/app/config/"
            readOnly: true
      volumes:
        - name: config
          configMap:
            name: codest-api-config
