name: Build

on: workflow_dispatch

env:
  CODEST_API_NAME: codest-api
  CODEST_API_IMAGE: ghcr.io/r3nnyweb/codest-api
  CODEST_RUNNER_NAME: codest-runner
  CODEST_RUNNER_IMAGE: ghcr.io/r3nnyweb/codest-runner
  CODEST_USER_API_NAME: codest-user-api
  CODEST_USER_API_IMAGE: ghcr.io/r3nnyweb/codest-user-api
  CODEST_FRONTEND_NAME: codest-front
  CODEST_FRONTEND_IMAGE: ghcr.io/r3nnyweb/codest-front

jobs:

  build-codest-api:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.TOKEN}}
    - name: Setup Buildx
      uses: docker/setup-buildx-action@v2
      with:
        driver-opts: |
          image=moby/buildkit:v0.11.2
    - name: Build Codest-api
      uses: docker/build-push-action@v4
      with:
        context: ./
        file: ./${{env.CODEST_API_NAME}}/Dockerfile
        push: true
        tags: |
          ${{env.CODEST_API_IMAGE}}:latest
          ${{env.CODEST_API_IMAGE}}:${{ github.sha }}
        cache-from: type=gha,scope=${{env.CODEST_API_NAME}}
        cache-to: type=gha,mode=max,scope=${{env.CODEST_API_NAME}}

  build-codest-runner:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.TOKEN}}
    - name: Setup Buildx
      uses: docker/setup-buildx-action@v2
      with:
        driver-opts: |
          image=moby/buildkit:v0.11.2
    - name: Build Codest-runner
      uses: docker/build-push-action@v4
      with:
        context: ./
        file: ./${{env.CODEST_RUNNER_NAME}}/Dockerfile
        push: true
        tags: |
          ${{env.CODEST_RUNNER_IMAGE}}:latest
          ${{env.CODEST_RUNNER_IMAGE}}:${{ github.sha }}
        cache-from: type=gha,scope=${{env.CODEST_RUNNER_NAME}}
        cache-to: type=gha,mode=max,scope=${{env.CODEST_RUNNER_NAME}}

  build-codest-user-api:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.TOKEN}}
    - name: Setup Buildx
      uses: docker/setup-buildx-action@v2
      with:
        driver-opts: |
          image=moby/buildkit:v0.11.2
    - name: Build Codest-user-api
      uses: docker/build-push-action@v4
      with:
        context: ./
        file: ./${{env.CODEST_USER_API_NAME}}/Dockerfile
        push: true
        tags: |
          ${{env.CODEST_USER_API_IMAGE}}:latest
          ${{env.CODEST_USER_API_IMAGE}}:${{ github.sha }}
        cache-from: type=gha,scope=${{env.CODEST_USER_API_NAME}}
        cache-to: type=gha,mode=max,scope=${{env.CODEST_USER_API_NAME}}

  build-codest-frontend:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.TOKEN}}
    - name: Setup Buildx
      uses: docker/setup-buildx-action@v2
      with:
        driver-opts: |
          image=moby/buildkit:v0.11.2
    - name: Build Codest-user-api
      uses: docker/build-push-action@v4
      with:
        context: ./${{env.CODEST_FRONTEND_NAME}}
        file: ./${{env.CODEST_FRONTEND_NAME}}/Dockerfile
        push: true
        tags: |
          ${{env.CODEST_FRONTEND_IMAGE}}:latest
          ${{env.CODEST_FRONTEND_IMAGE}}:${{ github.sha }}
        cache-from: type=gha,scope=${{env.CODEST_FRONTEND_NAME}}
        cache-to: type=gha,mode=max,scope=${{env.CODEST_FRONTEND_NAME}}
