name: CI-CD for Runner
on: workflow_dispatch

env:
  NAME: codest-runner
  IMAGE: ghcr.io/r3nnyweb/codest-runner

jobs:

  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.TOKEN}}
    - name: Setup Buildx
      uses: docker/setup-buildx-action@v2
      with:
        driver-opts: |
          image=moby/buildkit:v0.11.2
    - name: Build Codest-runner
      uses: docker/build-push-action@v4
      with:
        context: ./
        file: ./${{env.NAME}}/Dockerfile
        push: true
        tags: |
          ${{env.IMAGE}}:latest
          ${{env.IMAGE}}:${{ github.sha }}
        cache-from: type=gha,scope=${{env.NAME}}
        cache-to: type=gha,mode=max,scope=${{env.NAME}}

  deploy:
      name: Deploy
      needs: [ build ]
      runs-on: ubuntu-latest
      steps:
        - name: Set the Kubernetes context
          uses: azure/k8s-set-context@v2
          with:
            method: service-account
            k8s-url: https://109.195.163.201:16443
            k8s-secret: ${{ secrets.KUBERNETES_SECRET }}

        - name: Deploy to the Kubernetes cluster
          uses: azure/k8s-deploy@v1
          with:
            namespace: default
            manifests: |
              ${{env.NAME}}/k8s/app.yaml
              k8s/ingress.yaml
            images: |
              ghcr.io/r3nnyweb/codest-runner:${{ github.sha }}